version: "3.2"

services:
  geolocate:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"

  geolocate_spec:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    entrypoint: [ "bundle", "exec", "rspec", "-fd" ]
    command: [ "spec" ]